#!/usr/bin/python -O

import sys
import json

from linkedin_wrapper import get_company_updates
from Common import flatten

print json.dumps( flatten(get_company_updates(cid) for cid in sys.argv[1:]),
                  indent=4 )

