#!/usr/bin/python -O

import sys
import json

from linkedin_wrapper import get_company
from Common import flatten


print json.dumps( flatten(get_company(cid) for cid in sys.argv[1:]),
                  indent=4 )


