#!/usr/bin/python -O

import sys
import json

from linkedin_wrapper import get_profile


ids = sys.argv[1:] if len(sys.argv) > 1 else [None]
profiles = [get_profile(uid) for uid in ids]

print json.dumps( { '_total' : len(profiles), 'values' : profiles}, indent=4 )

