#!/usr/bin/python -O

import sys
import json

from linkedin_wrapper import get_company_by_name
from Common import flatten

print json.dumps( flatten(get_company_by_name(cname)
                              for cname in sys.argv[1:]),
                  indent=4 )
