#!/usr/bin/python -O

import sys
import json

from linkedin_wrapper import get_people_updates_by_url
from Common import flatten

print json.dumps( flatten(get_people_updates_by_url(url) for url in sys.argv[1:]),
                  indent=4 )

