#!/usr/bin/python -O

import sys
import json
from datetime import datetime
from FileUtils import getpermission

def ts2str(timestamp):
    """ convert timestamp to string """
    dt = datetime.fromtimestamp(timestamp * 0.001)
    return dt.strftime("%m %d %H:%M")


def gen_filespec(fs):
    return "%s%-10s  %-8s%-8s%-6s%-12s%-20s" % (
         'd' if fs.get("type", "FILE") == "DIRECTORY" else '-',
         getpermission(fs.get("permission", "000")),
         fs.get("owner", "<no user>"),
         fs.get("group", "<no group>"),
         fs.get("length", 0),
         ts2str(fs.get("modificationTime", 0)),
         fs.get("pathSuffix", "<no name>"))

fs_list = json.load(sys.stdin)["FileStatuses"]["FileStatus"]
print "\n".join(gen_filespec(fs) for fs in fs_list)

